### ISSUE TITLE
`current-change` event is duplicated on <el-table> and <el-pagination>

### ISSUE THREAD

**Issue by choi4450** [zollero/el-search-table-pagination#11]
`current-change` event namespace is duplicated on `<el-table>` and `<el-pagination>`.
so, we have to compare whether the type of the first argument of event is an object or a number.

Can you fix the event name or have another solutions?

http://element.eleme.io/#/en-US/component/table#table-events
http://element.eleme.io/#/en-US/component/pagination#events

| Event Name | Element | Description | Parameters |
| -- | -- | -- | -- |
| current-change | `<el-table>` | triggers when current row changes | currentRow, oldCurrentRow |
| current-change | `<el-pagination>` | triggers when `current-page` changes | the new `current-page` |

**Comment by zollero** [comment]
Hi, thx for the good question.

Currently, `el-search-table-pagination` has catch the `current-change` event of `<el-pagination>` and do some handling (change page no and fire a ajax request) in `el-search-table-pagination`. 
So, you only can get the `current-change` event of `<el-table>`  on `el-search-table-pagination` component, and cannot get the `current-change` event of `<el-pagination>`.

**Comment by choi4450** [comment]
I was mistaken. when the page was changed, row is unselected. so and the event occurred.
Thanks.
