### ISSUE TITLE
如果只想使用表单应该怎样写呢？

### ISSUE THREAD

**Issue by wuxianqiang** [zollero/el-search-table-pagination#13]
如果只想使用表单，不想使用表格和分页，应该怎样写呢？

**Comment by zollero** [comment]
请参考这个例子： https://codepen.io/zollero/pen/QrKEzX

**Comment by zollero** [comment]
只是目前，` <el-search-form>` 只支持 `el-input`，`el-select` 和 `el-datepicker` 这三种组件，不支持其他其他组件。

所以，如果你的业务需要其他组件，建议使用 `Element` 的原生组件来写。
