### ISSUE TITLE
elementUI-tabled的高级功能支持

### ISSUE THREAD

**Issue by liuhaiqian** [zollero/el-search-table-pagination#16]
貌似只有基础表格的例子，如果想实现高级表格呢，比如有排序功能的表格、统计的表格，是否也能支持配置。

**Comment by zollero** [comment]
@liuhaiqian 

请仔细阅读文档： https://github.com/zollero/el-search-table-pagination/blob/master/docs/zh_CN.md

支持 `Element` 中的大部分特性。参见下图。



![wx20180524-153102](https://user-images.githubusercontent.com/8801894/40470942-9b081c62-5f67-11e8-91e1-c741ae4478d9.png)
