### ISSUE TITLE
怎么在查询form中添加自己的按钮

### ISSUE THREAD

**Issue by hanzhenchaoGit** [zollero/el-search-table-pagination#20]
怎么在查询form中添加自己的按钮 比如我表格中需要新增数据  需要一个添加按钮 来弹出新增框 该怎么实现

**Comment by zollero** [comment]
直接在 <el-search-table-pagination> 标签内写你想呈现的内容，<el-search-table-pagination> 内的内容会被显示在 form 和 table 中间。参考下面这个：

```
<el-search-table-pagination
      type="local"
      :data="tableData"
      :page-sizes="[5, 10]"
      :columns="columns"
      :form-options="formOptions">
      <div style="text-align: right;">
        <el-button>新增</el-button>
      </div>
</el-search-table-pagination>
```

效果是下面这个：
![image](https://user-images.githubusercontent.com/8801894/41389575-2d23114e-6fc4-11e8-98be-3c8e6465adc1.png)


全部代码看下面这个示例： https://codepen.io/zollero/pen/gKxYJa

**Comment by hanzhenchaoGit** [comment]
我想的是跟查询 重置按钮放在一起 显得版式好看点

**Comment by hanzhenchaoGit** [comment]
这个我觉得以后有必要实现一下吧  如果这是作为一个完整的增删改查列表组件的话  肯定是要有一个新增入口的

**Comment by hanzhenchaoGit** [comment]
我自己实现了

**Comment by zollero** [comment]
你很棒

**Comment by younglee1** [comment]
@hanzhenchaoGit 你好，请问这部分您怎么实现的呢，我现在也在做这部分，想参考一下，谢谢。

**Comment by hanzhenchaoGit** [comment]
我原来那种方式虽然实现了 但是最终觉得在版式上不太好  操作按钮和查询按钮就是应该分开 放到一块就会很丑 可以按照作者提供的那个方式添加按钮

**Comment by hanzhenchaoGit** [comment]
@younglee1 我原来那种方式虽然实现了 但是最终觉得在版式上不太好 操作按钮和查询按钮就是应该分开 放到一块就会很丑 可以按照作者提供的那个方式添加按钮

**Comment by younglee1** [comment]
好的，谢谢

**Comment by hanzhenchaoGit** [comment]
@younglee1 
table
![image](https://user-images.githubusercontent.com/20226394/42364414-aa8ffc94-812d-11e8-8c82-360eae549fd6.png)
search
![image](https://user-images.githubusercontent.com/20226394/42364432-b71a2b38-812d-11e8-987f-3e64e8f02a5b.png)
使用时
![image](https://user-images.githubusercontent.com/20226394/42364470-d297d5fe-812d-11e8-908d-bb8717925da9.png)
