### ISSUE TITLE
自定义操作列无法显示button

### ISSUE THREAD

**Issue by younglee1** [zollero/el-search-table-pagination#21]
您好，我在使用时候在表格最右侧加了一列操作列，想要在每一行加一个编辑和删除按钮，但是列能出来button却不能显示，请问是什么问题？
以下是我的代码：
<img width="499" alt="image" src="https://user-images.githubusercontent.com/11716601/42211640-a57c4f12-7ee6-11e8-9164-f0693bed5c06.png">
![image](https://user-images.githubusercontent.com/11716601/42211685-b9190b0a-7ee6-11e8-99fc-9b79cd51fdf8.png)

**Comment by zollero** [comment]
![image](https://user-images.githubusercontent.com/8801894/42212882-f3cb7fd2-7ee9-11e8-8ea5-ba3e19ce3ac4.png)

请阅读文档

https://github.com/zollero/el-search-table-pagination/blob/master/docs/zh_CN.md#slots

**Comment by younglee1** [comment]
你好，我确实是按照文档中格式来写的，最右侧也多出了一列，只是button没有显示出来

**Comment by zollero** [comment]
代码贴出来，不要截图

**Comment by younglee1** [comment]
<template>
    <div>
      <el-search-table-pagination
        type="local"
        :data="teamData"
        :page-sizes="[10, 20, 50]"
        :columns="columns"
        stripe
        highlight-current-row
        :form-options="formOptions">
          <el-table-column label="Operate" slot="append" width="200px">
            <template slot-scope="scope">
              <el-button
                size="mini">Edit</el-button>
              <el-button
                size="mini"
                type="danger">Delete</el-button>
            </template>
          </el-table-column>
        </el-search-table-pagination>
    </div>
</template>

**Comment by younglee1** [comment]
<div>
      <el-search-table-pagination
        type="local"
        :data="teamData"
        :page-sizes="[10, 20, 50]"
        :columns="columns"
        stripe
        highlight-current-row
        :form-options="formOptions">
          <el-table-column label="Operate" slot="append" width="200px">
            <template slot-scope="scope">
              <el-button
                size="mini">Edit</el-button>
              <el-button
                size="mini"
                type="danger">Delete</el-button>
            </template>
          </el-table-column>
        </el-search-table-pagination>
    </div>

**Comment by zollero** [comment]
这个应该是可以的。 https://codepen.io/zollero/pen/OEqGZy  你看看代码是不是其他地方有问题

**Comment by younglee1** [comment]
好的，我再看一下，谢谢了
