### ISSUE TITLE
Language change

### ISSUE THREAD

**Issue by amitavadeb** [zollero/el-search-table-pagination#28]
Hello,

How can I change the pagination language to English?

Thanks

**Comment by eebasadre20** [comment]
> Hello,
> 
> How can I change the pagination language to English?
> 
> Thanks

I'm not sure if you've already solved this but to let you know I solved this by using this:

```
import lang from 'element-ui/lib/locale/lang/en'
import locale from 'element-ui/lib/locale'
locale.use(lang)
```
