### ISSUE TITLE
能否支持模糊搜索呢- -

### ISSUE THREAD

**Issue by LDty** [zollero/el-search-table-pagination#3]
#

**Comment by zollero** [comment]
@LDty 你是指本地数据展示的时候，支持模糊搜索吗？

**Comment by LDty** [comment]
@zollero 恩恩,是本地数据模糊搜索.因为涉及到导入文件转json,然后渲染table 所以remote data 好像不方便用,具体可以看下http://120.79.50.93, 谢谢- -

**Comment by zollero** [comment]
@LDty OK，稍后添加一个 模糊搜索 的选项

**Comment by LDty** [comment]
@zollero 谢谢!

**Comment by zollero** [comment]
@LDty 新增了对本地数据的 `模糊搜索` 功能的支持，请更新至版本 `v.0.4.19`。

npm: https://www.npmjs.com/package/el-search-table-pagination

**Comment by LDty** [comment]
@zollero 多谢多谢!

**Comment by zollero** [comment]
@LDty 不客气
