### ISSUE TITLE
操作列对表中数据做修改后，怎么及时反映出来呢？

### ISSUE THREAD

**Issue by leonpun** [zollero/el-search-table-pagination#35]
例如，我对表格中某一行数据进行修改或者删除，异步操作后，表中数据还是之前的，怎么才能直接操作到封装表格中的的数据呢？

**Comment by leonpun** [comment]
remote 方式获取数据的

**Comment by zollero** [comment]
@leonpun 可以在修改或删除之后，手动调用 `searchHandler` 这个函数。文档：https://github.com/zollero/el-search-table-pagination/blob/master/docs/zh_CN.md#%E5%87%BD%E6%95%B0

**Comment by leonpun** [comment]
感谢！
