### ISSUE TITLE
请教大神，请问下list和total异步返回要怎么写呀？

### ISSUE THREAD

**Issue by changming1987117** [zollero/el-search-table-pagination#38]
请教大神，请问下list和total异步返回，fetch要怎么写呀？

**Comment by zollero** [comment]
@changming1987117 详细说下情况吧

**Comment by changming1987117** [comment]
我现在后台返回的时候list和total是异步返回来的，因为total很大，为了体验问题，list和total是两个接口返回来的
我只会这样写fetch
fetch(params){
       return new Promise(resolve => {
             return resolve(API.getTaskList(params));
       })
}
这样写的时候，貌似list和total一起返回才可以，
所以想请教下，异步的情况下是怎么写fetch，忘不吝赐教

**Comment by zollero** [comment]
你可以用promise把两个异步加载封装到一个promise里面，然后传给 `fetch` 属性。 https://github.com/zollero/el-search-table-pagination/blob/master/docs/zh_CN.md#%E5%B1%9E%E6%80%A7

![image](https://user-images.githubusercontent.com/8801894/49055422-716c2700-f232-11e8-88cb-4c697bde55b8.png)

**Comment by zollero** [comment]
示例如下：

`
function getData() {
  return new Promise((resolve, reject) => {
    Promise.all(
      // 这里用两个promise来获取list和total，然后封装在一起
    )
  })
}
`

**Comment by changming1987117** [comment]
非常感谢大神的回复，这种写法也是要等两个promise都执行完才会渲染表格数据吧，我希望的是任意一个执行完就开始渲染，因为count计算非常耗时，所以希望可以先把一页的数据展示出来，而不是等待count执行完毕才开始渲染表格，请问这样可以做到吗？
