### ISSUE TITLE
可以实现模糊查询吗？

### ISSUE THREAD

**Issue by LittleiTiot** [zollero/el-search-table-pagination#50]
表单可以实现模糊查询吗？

**Comment by zollero** [comment]
能详细说一下问题吗？

**Comment by LittleiTiot** [comment]
data() {
    return {
      faultDatas: [],
      formOptions: {
        inline: true,
        resetBtnText: 'Search',
        forms: [
          { prop: 'deviceName', label: '设备名称', placeholder: '请输入设备名称' },
        ],   
      },
      columns: [
        { prop: 'deviceName', label: '设备名称', minWidth: 100},
        { prop: 'faultDesc', label: '故障描述', minWidth: 100 },
        { prop: 'faultStartTime', label: '发生时间', minWidth: 100 },
        { prop: 'faultEndTime', label: '结束时间', minWidth: 100 }
      ]
    }
  },

就是当我按照设备名称来查询，不需要将设备名称输完全，比如电视机，我输入电视的时候也能够查询

**Comment by zollero** [comment]
模糊查询这个功能，前端还是一样的传参，主要是看你的后端接口支不支持你要的模糊查询，你还是跟你们的后端聊一下这个问题吧。

**Comment by LittleiTiot** [comment]
好的谢谢
