### ISSUE TITLE
设置table为remote的模式时，form的search按钮会抖动

### ISSUE THREAD

**Issue by pangxiaozi** [zollero/el-search-table-pagination#52]
设置table为local模式时，search按钮是正常的。如果设置为remote模式，点击分页的按钮与search的按钮，search按钮会抖动一下。同时表格上面的一行会消失。

**Comment by zollero** [comment]
具体能截个图看下变化吗？把问题复现一下

**Comment by pangxiaozi** [comment]
![IMG_1007](https://user-images.githubusercontent.com/42882440/62585919-c5fd9100-b8ed-11e9-8c1d-3946e3dd3b31.JPG)
点击搜索的button时，会自动向右扩展一下。抖动一下，然后马上缩回来。

**Comment by pangxiaozi** [comment]
是我搞错了。
