### ISSUE TITLE
多级联动的选择框取值和传参

### ISSUE THREAD

**Issue by Jane-Zhang24** [zollero/el-search-table-pagination#59]
多级联动的选择框，如机构和部门，机构选定后作为入参传给部门，load部门的下拉框内容。
两者都是remoteData，用的selectFetch。怎样动态获取一下拉框的取值并且作为入参传递给另一个下拉框？

**Comment by zollero** [comment]
这个暂时只能手动写input组件获取，组件还不支持你的这种场景
