### ISSUE TITLE
分页请求的时候怎么获取记录总数？

### ISSUE THREAD

**Issue by rucnevermore** [zollero/el-search-table-pagination#7]
比如后台记录总数是100条，前端定义每页显示10条，请求被封装成'GET /data/fetch?pageIndex=2&pageSize=10'，后端响应只包含了第11条到第20条记录，此时total值怎么得到？

**Comment by zollero** [comment]
@rucnevermore 默认接口中会返回一个结果集的总数字段给前端，因为前端每次分页请求数据，最多只能拿到当前页的数据，无法真正知道后端真正有多少条数据。这时候，只能是接口中加一个字段（total），把总数返回给前端。

**Comment by rucnevermore** [comment]
明白了，我后来也是这么实现解决了~

**Comment by lynnyenn** [comment]
请问一下，”接口中加一个字段（total）“，这段有实例可以参考吗？我一直无法把总数值传到前端，谢谢
